### ISSUE TITLE
Tell a joke if .lol is passed an argument.

### ISSUE THREAD

**Issue by sajoy** [sajoy/console-dot-lol#2]
Current behavior:
```
> console.lol();
> 😂
```

Desired behavior:
```
> console.lol('what is this?');
> How do trees get on line? They log in! 
> 😂
```

**Comment by gokulanv** [comment]
This is cool. Would like to work on this. May I contribute? @sajoy

**Comment by sajoy** [comment]
Hi @gokul0, go for it! I still need to write up some contribution guidelines, etc, but in the mean time, feel free to send questions my way and have at it!

**Comment by gokulanv** [comment]
@sajoy Do we need to take the jokes from a db or we shall put it in a static array and randomly fetch it?

**Comment by sajoy** [comment]
@gokul0 Let's keep it simple with either an array in the JS or a separate JSON file.

**Comment by gokulanv** [comment]
Hi @sajoy ,

This is done. Will send a PR shortly.
Do lemme know in case you need any changes.
